CC=gcc
mioEditor: main.c
	$(CC) main.c termFunc.c editorFunc.c -o mioEditor -Wall -Wextra -pedantic -std=c99
test1:
	./mioEditor TestInProgress/fileDaleggereUnaRiga.txt
test2:	
	./mioEditor TestInProgress/fileTabbato.txt
nuovo:
	./mioEditor
clean: 
	$(RM) mioEditor
